[산토리_한세_짱민] 웹서버 2 단계 - GET으로 회원가입 기능 구현
codesquad-members-2022/java-was pull request #28
Opened 2022-03-23 14:16 UTC by seyoung755

안녕하세요! 리뷰어님. 좋은 하루입니다. 👍 
 was 만들기 미션 2단계 구현하여 PR드립니다.

## 구현 기능 목록
- [x] /user/create로 들어오는 요청 처리하기
- [x] QueryString으로부터 parameter 분리하기

## 보완해야할 점
- [ ] `RequestHandler` 내부 기능을 분리해보기

감사합니다.

2022-03-25 15:55 UTC, ksundong requested changes
안녕하세요. 산토리_한세_짱민, 리뷰어 dion입니다.

2단계 미션 수행하느라 고생하셨습니다.

전반적으로 개선했으면하는 의견이 있어서, Request changes 를 드리고, 개선한 다음 다음단계를 진행해보는게 좋겠다는 생각이 들었습니다.

고생하셨습니다. 다음단계 진행하면서 같이 진행해보세요~

2022-03-25 15:55 UTC, ksundong commented on src/main/java/util/HttpRequestUtils.java
> +    }
:+1:

2022-03-25 15:55 UTC, ksundong commented on src/main/java/util/HttpRequestUtils.java
> +    }
`url` 을 받아서 `url` 을 `parse` 하는걸까요?

2022-03-25 15:55 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +    @Override
:+1:

2022-03-25 15:55 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +                queryParameter = HttpRequestUtils.parseUrl(url);
차라리 `split` 한 친구를 응답으로 받아서 처리해주는게 나았을 것 같네요.
또한 `queryParameter` 가 하나일까요? 여러개일 수 있을까요? 이름을 잘 생각해봅시다.

2022-03-25 15:55 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
이쪽 코드를 개선해보면 좋을 것 같네요.

2022-03-25 15:55 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
이 부분을 컨트롤러 개념을 차용하면 좋았을 것 같은데 어떻게 생각하시나요?

2022-03-25 15:55 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +    private void createUser(String queryString) {
`queryString` 을 직접적으로 받지 않게끔 개선해보세요.

2022-03-26 13:06 UTC, seyoung755 commented on src/main/java/util/HttpRequestUtils.java
> +    }
url로부터 queryString을 뽑아내는 함수이므로 getQueryString로 이름을 수정해보려고 합니다!

2022-03-26 13:12 UTC, seyoung755 commented on src/main/java/webserver/RequestHandler.java
> +                queryParameter = HttpRequestUtils.parseUrl(url);
아.. 위 메서드에서 차라리 split한 String 배열 형태로 받아서 처리하는 게 더 깔끔했겠네요 ! 위 parseUrl 메서드 이름도 단순히 getQueryString이 아니라 적절한 이름을 고민해보겠습니다!
그리고 queryParameter보다는 queryString이라고 쓰는 것이 더 자연스럽겠네요 !

2022-03-26 13:14 UTC, seyoung755 commented on src/main/java/webserver/RequestHandler.java
> +            }
넵 미션 3을 진행하면서 url 매핑과 해당 url에 대한 처리를 위해서 컨트롤러 개념을 도입해보려고 노력해보았습니다 !

2022-03-28 14:24 UTC, ksundong commented on src/main/java/util/HttpRequestUtils.java
> +    }
왜 뽑아내는데 `get~`이라고 이름지어주실까요?

2022-03-29 14:53 UTC, ksundong commented
내일 중으로 변경해서 올려주실 수 있을까요?

2022-03-30 01:45 UTC, leezzangmin commented
> 내일 중으로 변경해서 올려주실 수 있을까요?

안녕하세요 디온,
산토리 샐리 한세 짱민 이렇게 네명이 3 : 1로 팀을 이루다가 다시 2:2로 나누어져서 2단계까지의 저장소는 더이상 참조하지 않는 저장소입니다 ㅠㅠ 3단계를 끝내고 4단계를 진행중인데, 구조를 많이 리팩토링해서 2단계 코드가 거의 남아있지 않습니다,,, 친절히 리뷰해주셨지만 이 PR은 close 하도록 하겠습니다ㅠㅠ

2022-03-30 01:45 UTC, closed without merging