[Yan&BC] 웹서버 2 단계 - GET으로 회원가입 기능 구현
codesquad-members-2022/java-was pull request #33
Opened 2022-03-24 07:27 UTC by honeySleepr

안녕하세요~~ Yan & BC 입니다!

2단계 PR 드립니다. 잘 부탁드립니다. 🙇‍♂️🙇‍♂️

* 구현 과정에서 궁금한 점이 생겨 코멘트란에 질문 남겨두었습니다.

2022-03-24 07:28 UTC, honeySleepr commented on src/main/java/util/MimeUtils.java
> +    }
여기서 Map 초기화를 Map.of()를 사용하는 방법과 
static 블록을 사용하는 방법 중 어떤걸 더 추천하시나요?

2022-03-25 16:47 UTC, ksundong requested changes
안녕하세요. Yan&BC, 리뷰어 dion입니다.

2단계 미션을 수행하느라 고생많으셨습니다.

질문주신 내용에 답변 드렸습니다. 또, 구현상 아쉬운 부분이 있어서 Request change를 드리려고 합니다. 해당 부분을 해결하시고 다시 리뷰요청 주세요. 고생많으셨습니다.

2022-03-25 16:47 UTC, ksundong commented on README.md
>  ### index.html 호출 시 스레드가 여러개 생성되는 이유?
많이 공부해보시면 좋을 내용입니다. 블로그에도 작성해보시길 권해드려요.

2022-03-25 16:47 UTC, ksundong commented on README.md
> +## 미션 중 고민거리
학습한 내용도 많이 작성해주세요.

2022-03-25 16:47 UTC, ksundong commented on src/main/java/util/HttpRequestUtils.java
> +        DataBase.addUser(user);
`static` 메서드에서 `DB` 에 저장하는건 괜찮을까요??

2022-03-25 16:47 UTC, ksundong commented on src/main/java/util/MimeUtils.java
> +    }
`Map.of()` 를 추천드립니다.

2022-03-25 16:47 UTC, ksundong commented on src/main/java/util/MimeUtils.java
> +        contentType.put("js", HTML_CONTENT_TYPE);
왜 `js` 는 `HTML_CONTENT_TYPE` 인가요?

2022-03-25 16:47 UTC, ksundong commented on src/main/java/util/MimeUtils.java
> +    }
정상동작을 보장하는 테스트를 만들어보면 어떨까요?

2022-03-25 16:47 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
이 구조는 조금 고민해보세요.  적절한 구현일까요?

2022-03-25 16:47 UTC, ksundong commented on src/test/java/util/HttpRequestUtilsTest.java
> +    }
적절한 테스트인지 한 번 더 생각해봅시다. `Utility` 메서드인데 `Business` 가 들어가버리지 않았나요?

2022-03-28 07:25 UTC, KTH-96 commented on src/main/java/util/HttpRequestUtils.java
> +        DataBase.addUser(user);
여러곳에서 사용될 가능성이 있을거 같네요! 고쳐보겠습니다 피드백 감사드립니다:)

2022-03-28 07:25 UTC, KTH-96 commented on src/main/java/util/MimeUtils.java
> +        contentType.put("js", HTML_CONTENT_TYPE);
처음에 개발자도구에서 컨텐트 타입을 봤을때 js파일도 text/html 으로 사용하길래 그런줄 알았는데 찾아보니 application/javascript이었네요 추가하겠습니다 :)

2022-03-28 07:25 UTC, KTH-96 commented on src/main/java/util/MimeUtils.java
> +    }
넵 알겠습니다 :)

2022-03-28 07:25 UTC, KTH-96 commented on src/main/java/webserver/RequestHandler.java
> +            }
run메스드에서 처리하는게 아니라 UrlHandler란 클래스를 만들어 처리하겠습니다 :) 감사합니다

2022-03-28 07:25 UTC, KTH-96 commented on src/test/java/util/HttpRequestUtilsTest.java
> +    }
addUserInfo메서드를 이동시켜서 테스트 작성해보겠습니다 감사합니다 :)

2022-03-28 15:10 UTC, ksundong approved these changes
고생하셨습니다~

2022-03-28 15:10 UTC, ksundong commented on src/main/java/util/HttpRequestUtils.java
>              }
해당 `while` 조건에서 저 `if` 문이 동작하는 경우가 있나요?

2022-03-28 15:10 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            urlHandler.mapUrl(url);
`mapUrl` 이 잘 이해가지 않는 이름인 것 같아요.

2022-03-28 15:10 UTC, ksundong commented on src/main/java/webserver/UrlHandler.java
> +    /// user/create?userId=javajigi&password=password&~
요 주석은 왜 필요한가요?

2022-03-28 15:10 UTC, ksundong commented on src/main/java/webserver/UrlHandler.java
> +    }
이 메서드가 여기 있는건 적절할지도 생각해보면 좋겠습니다~

2022-03-28 15:11 UTC, merged

2022-03-29 01:51 UTC, honeySleepr reviewed
2차 피드백까지 신경써주셔서 감사합니다 디온!

2022-03-29 01:51 UTC, honeySleepr commented on src/main/java/webserver/UrlHandler.java
> +    /// user/create?userId=javajigi&password=password&~
앗 저희가 참고하려고 실수로 남겨놨네요;; 처리했습니다~

2022-03-29 01:51 UTC, honeySleepr commented on src/main/java/webserver/RequestHandler.java
> +            urlHandler.mapUrl(url);
더 적절한 이름을 생각해보겠습니다!

2022-03-29 01:51 UTC, honeySleepr commented on src/main/java/util/HttpRequestUtils.java
>              }
isNullOrEmpty 가 있어서 중복이었네요!

2022-03-29 01:51 UTC, honeySleepr commented on src/main/java/webserver/UrlHandler.java
> +    }
넵 고민해보겠습니다 :)