[헤이호 & 포키] 웹서버 3단계 - POST로 회원 가입
codesquad-members-2022/java-was pull request #37
Opened 2022-03-25 02:46 UTC by Seokho-Ham

안녕하세요 시간 내서 리뷰해주시는 점 항상 감사합니다!
2단계 리뷰해주신 내용들을 적용했고 3단계 요구사항들을 구현했습니다. 리뷰 부탁드립니다!
좋은 주말 보내세요😊

2022-03-27 05:04 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
몇 가지 코멘트 남겨보았는데요, 확인 부탁드릴게요

2022-03-27 05:04 UTC, wheejuni commented on src/main/java/db/DataBase.java
> +    }
한 줄 짜리 로직이고, 사용처가 한 군데밖에 없어서 괜한 분리라는 생각이 듭니다.

2022-03-27 05:04 UTC, wheejuni commented on src/main/java/model/User.java
> +        return new User(userInfo.get("userId"), userInfo.get("password"), userInfo.get("name"), userInfo.get("email"));
필요한 정보가 `userInfo` 에 하나라도 빠져있으면 어떻게 되는 거지요?

2022-03-27 05:04 UTC, wheejuni commented on src/main/java/webserver/HttpRequest.java
> +        }else{
컨벤션을 준수 합시다.

```suggestion
        } else {

2022-03-27 05:04 UTC, wheejuni commented on src/main/java/webserver/HttpRequest.java
> +    private String httpMethod;
`HttpMethod` 에 대한 추상화도 이번 단계에서 시도해 보셨으면 좋겠군요.

2022-03-27 05:04 UTC, wheejuni commented on src/main/java/webserver/HttpResponse.java
> +        dos.writeBytes("Content-Type: text/html;charset=utf-8\r\n");
항상 `text/html` 만 리턴하게 되는 걸까요?

2022-03-27 14:41 UTC, Seokho-Ham commented on src/main/java/db/DataBase.java
> +    }
무조건적으로 메서드로 분리하는 버릇이 있었네요ㅎㅎ 수정하겠습니다!

2022-03-27 14:43 UTC, Seokho-Ham commented on src/main/java/webserver/HttpRequest.java
> +    private String httpMethod;
Enum을 사용해서 추상화해보겠습니다.

2022-03-27 14:44 UTC, Seokho-Ham commented on src/main/java/webserver/HttpResponse.java
> +        dos.writeBytes("Content-Type: text/html;charset=utf-8\r\n");
현재는 그렇게 해놨는데 HttpMethod를 enum으로 만들면서 Context-Type도 함께 만들려고 했습니다.

2022-03-28 04:28 UTC, Seokho-Ham commented
리뷰해주신 내용을 바탕으로 리팩토링을 진행했습니다!
확인 후 머지 부탁드립니다~
오늘도 좋은 하루 보내세요😊

2022-03-30 17:00 UTC, honux77 commented
요거 제가 머지할게요~

2022-03-30 17:00 UTC, merged