[nathan & jerry] 웹서버 3단계 - POST로 회원 가입
codesquad-members-2022/java-was pull request #38
Opened 2022-03-25 02:50 UTC by nathan29849

안녕하세요 nathan과 jerry입니다.

3단계 미션 PR을 보냅니다. 

항상 감사드립니다.

--- 
## 기능요구사항
- [x] HTML form을 통해 회원가입을 할 수 있다.
- [x] 가입 후 index.html 페이지로 이동한다.
- [x] 같은 ID로 가입을 시도할 경우 가입되지 않고 가입 페이지로 이동한다.

## 한 일 
refactor : Request, Response 클래스를 통해 기존 Handler의 역할 분담 
docs : 미션 3단계에서 학습한 내용 README 정리
 feat : 유저 회원가입 및 중복아이디 체크

2022-03-27 05:15 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
간단한 커멘트 몇 개 남겼습니다. 확인 부탁드려요~

2022-03-27 05:15 UTC, wheejuni commented on src/main/java/util/Request.java
> +	private String[] parseRequestURL() {
단순히 문자열 배열이 나가는 것보다 뭔가 필요한 정보가 필드들로 선언되어 있는, 충분한 추상화가 이뤄진 클래스가 리턴 타입이었으면 좋겠군요.
`private` 이라 쉽게 생각할 수도 있지만 사실 이런 종류의 리턴 타입은 받아쓰는 입장에서는 굉장히 불안하긴 하죠.
길이도 정해진 게 없고, 안에 무슨 내용이 들었는지도 모르겠고... 몇번 인덱스에 뭐가 들었는지 상수로 선언해 두긴 했지만 그 뿐이고 사실 그게 어떤 내용인지는 확신할 길은 없어 보이긴 하니까요. 
지금 이 메서드에 의존하는 다른 로직이 어떤 정보들을 필요로 하는지 한번 검토해보셨나요? 그렇다면 그에 따른 추상화도 고민하실 수 있을 것 같은데요.
한번 시도해 보시는 것도 좋겠네요. 물론 다음 단계에서 하셔도 됩니다.

2022-03-27 05:15 UTC, wheejuni commented on src/main/java/util/Request.java
> +	}
이런 방식의 비교를 할 거라면 `HttpMethod` 라는 열거형이나 클래스가 있으면 좋겠죠?

2022-03-27 05:15 UTC, wheejuni commented on src/main/java/util/Response.java
> +	}
앞으로 수많은 종류의 status code를 지원해야 할 겁니다. 
아래와 같이 밈 상태 코드가 새로 생겨날 수도 있어요.
https://developer.mozilla.org/ko/docs/Web/HTTP/Status/418

그때마다 메서드가 추가돼야 할까요? 더 좋은 구조를 고민해 주시기 바랍니다.

2022-03-30 07:15 UTC, jeremy0405 commented on src/main/java/util/Request.java
> +	}
4단계를 진행하면서 HttpMethod enum class를 생성했습니다!!

2022-03-30 07:16 UTC, jeremy0405 commented on src/main/java/util/Response.java
> +	}
4단계 진행하면서 리팩토링을 통해 범용적인 메서드 설계를 해서 `response.write()` 메서드로 모든 것이 가능하도록 처리 했습니다!

2022-03-30 07:17 UTC, jeremy0405 commented
리뷰어님 리뷰 감사합니다! :)

코드 리뷰를 바탕으로 4단계 진행하면서 코드를 개선하였습니다.
4단계 미션 구현에 따라서 머지 하겠습니다!

감사합니다.

2022-03-30 07:17 UTC, merged