[민지노 & 준] 웹서버 2단계 - GET으로 회원 가입
codesquad-members-2022/java-was pull request #41
Opened 2022-03-25 08:50 UTC by Minzino

# java-was

Java Web Server Project for CodeSquad Members 2022

<br/><br/><br/>

## ✍🏻 요구사항

GET방식을 통해 회원가입을 진행할 수 있다.

<br/><br/><br/>

## To-do List

- [x] index.html로 접속하면 회원가입 폼 파일을 내려준다.
- [x] 이 폼을 통해 회원가입을 할 수 있다.
- [x] 한글이 정확하게 입력되고 있는지 확인해야 한다.
- [x] 가입한 회원 데이터는 리스트 형태로 저장한다.
<br/><br/><br/>

## 구현 중 학습한 내용

<details>
<summary>📝 1단계 학습내용</summary>
<br/>

- HTTP 동작방식에 대해 생각을 정리하는 시간을 가졌습니다. [그림 출처](https://pearlluck.tistory.com/117)
    1. 사용자가 브라우저에 URL 주소 입력<br/><br/>
    2. DNS서버에 의해 IP주소 찾음
        - `IP주소`: 컴퓨터 네트워크에서 장치들이 서로 인식하기 위한 특수번호
        - `MAC주소`: 네트워크 인터페이스에 할당된 고유 식별자(변경불가)
        - `ARP(Address Resolution Protocol`: 주소 결정 프로토콜(목적지 IP주소값을 가지고 상대방의 MAC주소를 찾음)<br/><br/><br/>
    3. 웹서버와 TCP 연결시도
        - 3-way-handshaking: 클라이언트와 서버간에 신뢰성 있는 연결을 위한 3번의 패킷쿄환 과정
            1. Client -> Server: 처음으로 패킷을 보낸다(SYN)
            2. Server -> Client: Client가 보낸거 잘받았고(ACK), 내가 처음으로 패킷을 보낸다(SYN)
            3. Client -> Server: Server가 보낸거 잘받았고(ACK) 이제 서로 데이터(`HTTP메세지`)를 보낼 준비 완료
               ![3way-handshake](https://t1.daumcdn.net/cfile/tistory/225A964D52F1BB6917)
               <br/><br/><br/>
    5. 웹서버와 http메세지 주고받음
        - HTTP : Hyper Text Transfer Protocol, Hyper Text를 전송하기 위한 프로토콜, Request&Response 주고받는 역할 클라이언트가 서버에 요청을 보내면, 그에
          맞는 응답 결과를 돌려주고, 클라이언트는 사용자에게 서버로부터 응답받은 결과를 보여주는 것
          ![http통신](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbMcIdM%2FbtqDcdvjYXA%2FVML0aacRlfdAw41dD3f1LK%2Fimg.png)
          ​
        - 4-1. 클라이언트 -> 서버 : request 전송
            - 요청메세지 : 메소드/ 요청UTL / HTTP버전
        - 4-2. 서버 -> 클라이언트 : response 받음
            - 응답메세지 : HTTP버전/상태코드/사유구절
              <br/><br/><br/>
    6. 웹서버와 TCP연결 해제
        - 4-way-handshaking : 클라이언트와 서버간에 양쪽다 연결을 종료시킨다
            1. Client->Server : 처음으로 종료한다는 패킷을 보낸다(FIN)
            2. Sever ->Client : Client가 보낸거 잘받았고(ACK)
            3. Sever ->Client : Server가 처음으로 종료한다는 패킷을 보낸다(FIN)
            4. Client-> Server : Server가 보낸거 잘받았고(ACK) 이제 서로연결 종료한다.
               ![4way-handshake](https://t1.daumcdn.net/cfile/tistory/2152353F52F1C02835)                
               ​ 이 과정에서 생긴 궁금점은 현재 로컬(내 PC)에서 웹서버를 실행하여 웹브라우저로 접근을 했을 때 내 PC에서 동작중인 웹서버에 접속을 하는 데에도 TCP 커넥션을 맺는지
               궁금했습니다.</br>
               와이어샤크로 확인해본 결과 로컬 내에서 접속을 해도 커넥션을 맺는 것을 확인할 수 있었습니다. ​
               ![와이어샤크 확인 결과](https://user-images.githubusercontent.com/86910955/159453454-adc91804-434e-4e1e-aa8d-0e30b8b4c991.png)
               ​ ​
               <br/><br/>

</details>

<details>
<summary>📝 2단계 학습내용</summary>
<br/>

### URL파싱과 데이터 전송까지만 구현했기 때문에 url이 리다이렉션 되지는 않습니다.
- GET 방식 데이터 전송
  - URL 뒤에 ? 마크를 통해 데이터를 전송한다.
  - 2개 이상의 key, value 쌍 데이터를 보낼 때는 & 마크로 구분한다.
  - GET 방식의 요청은 캐싱 방식을 사용하기 때문에 다른 데이터 전송보다 속도가 빠르다.
<br/><br/><br/>

`학습하면서 GET 방식이 왜 더 빠를까` 를 고민하다 이것저것 실험해 보았습니다. 아직 구현하지 못했지만 학습한 내용은 다음과 같습니다.
- 데이터가 변경되지 않는 상황에서 굳이 같은 데이터를 내려줄 필요가 없기 때문에 다양한 캐싱 전략을 사용한다. 캐싱을 위해서는 cache-control과 last-modified-since와 같은 값들을 사용할 수 있다.

`웹 브라우저에는 캐시를 저장하는 저장소가 있는데 이 경우 두 번쨰 요청시 저장소를 통해 네트워크 통신을 하지 않아도 되며, 하드디스크를 통해 바로 데이터를 가져올 수 있다.
`
<br/><br/><br/>

- cache-control, 을 통해 캐시가 유효한 시간을 명시한다.
- Last modified-since를 통해 데이터가 변경된 지 알 수 있다.

![http이미지](https://user-images.githubusercontent.com/86910955/160075123-4d0d2342-dc94-4703-9f6a-ba5496a007ae.png)

참고자료

- https://itstory.tk/entry/Spring-MVC-LastModified-IfModifiedSince-%EC%BA%90%EC%8B%9C-%EC%84%A4%EC%A0%95
- https://stackoverflow.com/questions/10498135/last-modified-header-in-mvc

<br/><br/><br/><br/>

스프링에서 어떻게 이를 사용할 수 있을까 하고 찾아보던 중 아래와 같은 방식을 찾았지만 아직까지 정확하게 어떻게 사용해야 할지는 감이 잘 잡히지 않습니다.
3, 4단계 미션을 수행해 가면서 방법을 찾아보겠습니다.

</details>

2022-03-27 14:26 UTC, ksundong requested changes
안녕하세요. 민지노 & 준, 리뷰어 dion입니다.

2단계 미션을 수행하느라 고생많으셨습니다.

다만, 이번 미션에서 목표하고자 하는 `HTTP` 에 대한 학습이 부족한 부분이 많이 보여서, 변경요청을 드립니다. 코멘트 받은 내용을 반영해주시고, 리뷰요청주세요. 고생하셨습니다.

2022-03-27 14:26 UTC, ksundong commented on .idea/git_toolbox_prj.xml
> +<?xml version="1.0" encoding="UTF-8"?>
이 파일이 버전관리 되어야 하는 이유가 있나요?

2022-03-27 14:26 UTC, ksundong commented on README.md
> +<br/><br/><br/>
`br` 태그를 많이 써주시는 이유가 있나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/db/DataBase.java
>  }
이 코드는 왜 바꿔주셨나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/db/DataBase.java
> +                .orElseThrow();
왜 `orElseThrow` 에 아무 인자도 넘겨주지 않으셨나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/Extention.java
> +    HTML("html", "text/html;charset=utf-8"),
왜 utf-8을 사용해주셨나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/Extention.java
> +    Extention(String extension, String mimeType) {
빈 줄로 구분해주세요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/Extention.java
>      public static String of(String inputType) {
`of` 라는 이름을 주신 이유가 있나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/Extention.java
> +                .filter(headerType -> euqalTo(headerType.mimeType, inputType))
`equalTo` 메서드가 필요한 이유가 있나요? 이상한 흐름으로 보여요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/Extention.java
> +    NONE("", "");
`NONE` 이 필요한 이유가 있나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/HeaderType.java
> +    ORIGIN("Origin"),
이게 현재 다 필요한 헤더인가요? 왜 이렇게 헤더를 추가해주셨나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/HeaderType.java
>      NONE("");
`NONE` 이 필요한 이유가 있나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
커스텀 헤더의 경우에는 어떻게 추가해줄 수 있나요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
`orElse` 와 `orElseGet`의 차이에 대해서 알고 계신가요? `orElse` 를 사용해주신 이유는 무엇인가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/util/SpecialCharacters.java
> +    public static final String QUESTION_MARK = "?";
형태를 표현하는 용어 대신 의미를 담아서 네이밍 해주세요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Configuration.java
> +public class Configuration {
이 클래스가 해야 하는 일이 이름만으로 명확하지 않아보여요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Configuration.java
> +    }
매번 호출할 때마다 맵을 만들고, 맵을 채우고 해야할까요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    private String UUID;
왜 필요한건가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    private Map<HeaderType, String> map;
무슨 Map인가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    private String email;
`Request` 가 담기에는 너무 구체적인 정보 아닌가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/Configuration.java
> +public class Configuration {
또한 이 클래스의 인스턴스가 매번 생성될 수 있을 것 같은데, 그럴 필요가 없어보여요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            String requestUrl = request.getHeaderType(REQUEST_URL);
`HTTP` 스펙상 `URL` 이 `Header` 인가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            if (requestUrl.startsWith(JOIN_PATH) && requestUrl.endsWith(Extention.HTML.getType())) {
url이 정말 많아지면 이를 어떻게 해결할 수 있을지도 생각해보면 좋을 것 같아요.

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +                Map<String, String> params = HttpRequestUtils.parseQueryString(queryString);
어떤 `param` 인가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
이 구조라면 `else` 를 쓰지 않는 방법은 없을까요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +    private Map<HeaderType, String> getHeaders(BufferedReader bufferedReader) throws IOException {
`BufferedReader` 를 받으면 어떤 문제가 생길까요? `stream` 은 어떻게 다루는게 좋을까요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +        Map<HeaderType, String> headers = new ConcurrentHashMap<>();
`ConcurrentHashMap` 을 사용해주신 이유는 무엇인가요?

2022-03-27 14:26 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +        }
`while` 조건이 너무 복잡한데요. 개선해봅시다.

2022-03-27 14:56 UTC, devjun10 commented on README.md
> +<br/><br/><br/>
조금 더 보기 깔끔하게 하기 위해 사용했는데 따라야 하는 규약이 있을까요?

2022-03-27 14:56 UTC, devjun10 commented on src/main/java/db/DataBase.java
>  }
2단계 요구사항에 List<User> 에 담으라고 해서 List를 사용했습니다.

2022-03-27 14:57 UTC, devjun10 commented on src/main/java/db/DataBase.java
> +                .orElseThrow();
추후에 커스텀 예외를 만들려고 놔뒀는데 수정하겠습니다.

2022-03-27 14:58 UTC, ksundong commented on README.md
> +<br/><br/><br/>
꼭 지켜야한다는 규약같은게 있지는 않은데요.
왜 빈 줄이 이렇게 많이 들어가야만 했는지가 궁금했어요.

2022-03-27 15:05 UTC, devjun10 commented on src/main/java/model/Extention.java
>      public static String of(String inputType) {
Extention.of(inputType) 을 들어온 타입의 확장자 라는 이름으로 사용하려고 했습니다.

2022-03-27 15:07 UTC, devjun10 commented on src/main/java/model/Extention.java
> +                .filter(headerType -> euqalTo(headerType.mimeType, inputType))
headerType->headerType. mimeType.equals(inputType) 으로 달면 너무 길어져서 그랬습니다. 혹시 더 좋은 방법이 있을까요?

2022-03-27 15:10 UTC, devjun10 commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
lazy 의 차이로 알고 있습니다. 그냥 타입이 안 들어올 경우 바로 NONE을 넣어주려고 했습니다. 저 부분 수정하겠습니다.

2022-03-27 15:15 UTC, devjun10 commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
어떻게 추가 한다는 것의 의미가 잘 이해가지 않습니다.

2022-03-27 16:01 UTC, devjun10 commented on src/main/java/model/Extention.java
> +    HTML("html", "text/html;charset=utf-8"),
헤더의 Content-Type에을 Content-Type: text/html; charset=utf-8 을 안 넣으면 한글이 깨질 때가 있다고 해서 넣었습니다. 저희가 실행할 때도 별다른 글자 깨짐은 없었는데 빼도 되는 걸까요?

2022-03-27 16:16 UTC, ksundong commented on src/main/java/model/Extention.java
> +    HTML("html", "text/html;charset=utf-8"),
`UTF-8` 에 대해서 학습해보시면 좋을 것 같아요.

2022-03-27 16:18 UTC, ksundong commented on src/main/java/model/Extention.java
> +                .filter(headerType -> euqalTo(headerType.mimeType, inputType))
`headerType.mimeTypeEquals(inputType)` 같은 느낌은 어떨까요?
제가 코드가 다 기억나는게 아니라...

2022-03-27 16:18 UTC, ksundong commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
HTTP Header 에는 사용자 정의 Header가 들어올 수 있습니다. 이를 어떻게 대처해주실 것인가요?

2022-03-27 16:19 UTC, ksundong commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
음 왜 수정해야한다고 생각하셨나요??

2022-03-27 17:13 UTC, devjun10 commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
답변 주셔서 감사합니다 🙏. 사용자 정의 헤더가 잘 추가되지 않기 때문에 enum을 사용했습니다. 그리고 만약 사용자 정의 헤더가 들어올 경우 추가하면 되지 않을까요?

2022-03-27 17:27 UTC, devjun10 commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
이 경우 단순히 값만 반환할 경우 orElse를 써도 되지만 orElseGet을 사용할 경우 조금 더 선택지가 많아질 것이라 판단했기 때문입니다.

2022-03-28 14:38 UTC, ksundong commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
어떻게 추가해줄 수 있나요?

2022-03-28 14:39 UTC, ksundong commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
조금 의아한 답변인데요. 조금 더 선택지가 많아진다를 구체적으로 설명해주실 수 있을까요?

2022-03-28 14:47 UTC, devjun10 commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
사용자 정의 헤더가 자주 사용되는 줄 몰랐습니다. 열거형을 추가하는거 말고 다른 방법이 있을까요?

2022-03-28 15:03 UTC, ksundong commented on src/main/java/model/HeaderType.java
>  public enum HeaderType {
보통은 열거형은 predefined에는 적합하지만, 이렇게 다양한 상황에 대응할 필요가 있을 경우에는 적합한 선택이 아닙니다.
그런 문제가 있다 정도만 생각하시고, 다음 단계 진행하셔도 무방합니다.
한 번 jun이 고민해보시고 나름의 정답을 찾아보시길 바라겠습니다~

2022-03-28 15:05 UTC, devjun10 commented on src/main/java/model/HeaderType.java
> +                .orElse(NONE);
선택지가 많아진다고 말했던 건 예외가 발생하지 않으면 위에 none() 메서드가 아에 실행이 안된다. 바로 실행되는 것 보다 한 가지 경우의 수가 더 많다, 더 효율적이다 이런 의미였습니다. 혹시 어떤 키워드로 공부하면 될까요?

2022-03-28 15:20 UTC, ksundong approved these changes
고생하셨습니다.

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/http/HttpMethod.java
> +            System.out.println(httpMethod.name());
이건 왜 출력해주시나요?

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/http/Series.java
> +}
이정도까지 필요한 이유가 있나요??

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/http/HttpVersion.java
> +                .orElseThrow(()->new IllegalArgumentException("해당 버전이 존재하지 않습니다."));
포매팅 신경써주세요~

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/request/HttpHeader.java
> +    private static final String COLON = ": ";
변수의 모양을 설명하기 보단 이것이 무엇인지 설명하는 네이밍을 작성해주세요.

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/request/HttpHeader.java
> +    public HttpHeader(BufferedReader bufferedReader) throws IOException {
생성자에 `BufferedReader` 를 인자로 받아주신 이유가 있나요?

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/request/HttpRequest.java
> +    private static final StringBuffer sb = new StringBuffer();
`sb` 같은 축약어는 지양해주시고, 이것이 여기서 관리되는 이유는 무엇인가요?

2022-03-28 15:20 UTC, ksundong commented on src/main/java/model/request/HttpRequestBody.java
> +}
이 클래스가 필요한 이유는 무엇인가요?

2022-03-28 15:20 UTC, ksundong commented on src/main/java/webserver/WebServer.java
> +    private static final int DEFAULT_PORT = 8082;
바뀐 이유가 있나요?

2022-03-28 15:20 UTC, merged

2022-03-28 18:14 UTC, devjun10 commented on src/main/java/model/request/HttpHeader.java
> +    public HttpHeader(BufferedReader bufferedReader) throws IOException {
윗 댓글에서도 아직 답을 못 찾았는데 BufferReader를 인자로 받으면 안되는 이유가 있을까요?

2022-03-28 18:18 UTC, devjun10 commented on src/main/java/model/http/Series.java
> +}
학습하면서 스프링 내부 구현이 어떻게 돼 있나 궁금해 찾아보면서 사용했습니다. 조그마한 프로젝트 하면서 왜 그렇게 하냐고 하시면 딱히 대답 못할 것 같은데, 굳이 이유를 찾자면 조금 더 명시적으로 나타낼 수 있기 때문에 사용해보았습니다.

2022-03-28 18:19 UTC, devjun10 commented on src/main/java/model/http/Series.java
> +}
학습하면서 스프링 내부 구현이 어떻게 돼 있나 궁금해 찾아보면서 사용했습니다. 굳이 이유를 찾자면 조금 더 명시적으로 나타낼 수 있기 때문에 사용해보았습니다.

2022-03-28 18:20 UTC, devjun10 commented on src/main/java/model/request/HttpRequest.java
> +    private static final StringBuffer sb = new StringBuffer();
학습 차원에서 아래와 같은 메서드를 만들어 로그를 찍었습니다. 불필요하다 판단돼서 삭제했는데 삭제하지 않은 필드입니다.

<img width="812" alt="Screen Shot 2022-03-29 at 3 16 05 AM" src="https://user-images.githubusercontent.com/92818747/160461522-4c9f92e4-b239-44fd-b83e-c133eafb8365.png">

2022-03-28 18:21 UTC, devjun10 commented on src/main/java/webserver/WebServer.java
> +    private static final int DEFAULT_PORT = 8082;
80포트를 사용중이라 82 포트로 바꿨습니다.

2022-03-28 18:23 UTC, devjun10 commented
> 고생하셨습니다.

리뷰해주셔서 감사합니다.

2022-03-29 14:56 UTC, ksundong commented on src/main/java/model/request/HttpHeader.java
> +    public HttpHeader(BufferedReader bufferedReader) throws IOException {
테스트 코드를 짜보시면 어떤 것이 문제인지 꺠달으실 수 있을 것 같아요.
생성자가 생성을 하는 것이 아닌 reader를 읽어들이는 역할까지 수행하게 됩니다.
우리가 Java 코딩을 할 때도, Scanner를 도메인 객체에 넣어주지 않은 것처럼요.

2022-03-29 14:58 UTC, ksundong commented on src/main/java/model/request/HttpRequest.java
> +    private static final StringBuffer sb = new StringBuffer();
삭제했는데 삭제하지 않은 필드가 어떤 의미일까요??
잘 이해가 되지 않는 설명이네요~~

2022-03-29 14:58 UTC, ksundong commented on src/main/java/webserver/WebServer.java
> +    private static final int DEFAULT_PORT = 8082;
80포트를 점유하고 있던건 무엇이었나요?