[선을로 & 벅픽] 웹서버 3단계 - POST로 회원 가입
codesquad-members-2022/java-was pull request #42
Opened 2022-03-25 09:29 UTC by bugpigg

안녕하세요~ 선을로, 벅픽입니다.
웹서버 3단계 PR 입니다!

### 기능요구사항
 - [x] `http://localhost:8080/user/form.html` 파일의 HTML form을 통해 회원가입을 할 수 있다.
 - [x] 가입 후 index.html 페이지로 이동한다.
 - [x] 같은 ID로 가입을 시도할 경우 가입되지 않고 가입 페이지로 이동한다.

### 프로그래밍 요구사항
- [x] `http://localhost:8080/user/form.html` 파일의 form 태그 method를 get에서 post로 수정한다.
- [x] POST로 회원가입 기능이 정상적으로 동작하도록 구현한다.
- [x] 중복아이디를 처리하기 위해서 Map<Id, User> 로 회원목록을 관리한다.
- [x] 가입 후 페이지 이동을 위해 redirection 기능을 구현한다.

항상 좋은 리뷰 감사합니다~~

2022-03-27 15:00 UTC, ksundong requested changes
안녕하세요. 선을로 & 벅픽, 리뷰어 dion입니다.

3단계 미션을 수행하느라 고생많으셨습니다.

전체적으로 아쉬운 부분이 조금 있어서, 이 부분을 정리해보고 다음 단계를 진행하게 좋겠다는 생각이 들어 변경 요청을 드립니다. 코멘트를 참고해 수정해주시고, 리뷰 요청을 해주세요. 고생하셨습니다~

2022-03-27 15:00 UTC, ksundong commented on src/main/java/db/DataBase.java
> +            throw new IllegalArgumentException("중복된 회원 아이디 입니다.");
`IllegalArgumentException` 은 어떤 상황에서 발생해야하는 예외일까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/util/RequestLineUtil.java
> +        String[] strList = requestLine.split(" ");
`strList`는 무슨뜻인가요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
>          String line;
`변수 사용시점이 아닌 미리 선언해주신 이유가 있나요?`

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
> +        initURL();
`init` 이라는 것은 굉장히 어색하게 느껴집니다. `init` 은 언제써야 할까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
>      public Request(BufferedReader bufferedReader) throws IOException {
`BufferedReader` 를 생성자의 인자로 사용해주신 이유는 무엇인가요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
> +            String[] temp = line.split(" ");
`temp` 말고 좋은 이름은 없을까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
> +        while (!("").equals(line = bufferedReader.readLine())) {
불필요한 괄호는 제거해주는 것이 좋아보여요.

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    }
생성자가 너무 많은 일을 하지 않도록 해주세요.

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Request.java
>      }
메서드를 상태로 관리하는게 어땠을까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
>      }
도메인 로직을 여기서 수행시켜주신 이유는 무엇인가요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Response.java
> +    private static final Logger log = LoggerFactory.getLogger(Response.class);
도메인 객체에 로거가 필요한 이유는 무엇일까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Response.java
> +    private DataOutputStream dos;
`stream` 이 상태로 관리되어야 하는 이유가 있나요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/Response.java
> +    }
엄밀히 말하면 이것도 출력인데요. 우리가 자바 프로그래밍을 배울 때를 떠올려 봅시다.
`Response` 의 역할을 잘 나눠봅시다.

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    private static final String SIGN_UP_PAGE = "http://localhost:8080/user/form.html";
만약에 `host` 주소가 바뀌거나 `port` 가 바뀐다면 어떻게 될까요?

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    public void setRedirectSignUpPAGE() {
네이밍 컨벤션을 지켜주세요~ `~PAGE`

2022-03-27 15:00 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    }
`target` 보다는 좀더 명확한 이름을 지어주세요.

2022-03-28 01:40 UTC, fpzk5656 commented on src/main/java/db/DataBase.java
> +            throw new IllegalArgumentException("중복된 회원 아이디 입니다.");
사용자 정의 Exception을 활용해 좀 더 적절한 Exception으로 사용해보겠습니다!

2022-03-28 01:46 UTC, fpzk5656 commented on src/main/java/util/RequestLineUtil.java
> +        String[] strList = requestLine.split(" ");
일단 strList의 역할은 문자열을 분리할 목적으로 사용하였습니다.
strArray는 뭔가 어색하고, str은 배열이라 부르기 애매해서 strList라고 지었습니다.
splitedRequestLine으로 수정해볼까 합니다!

2022-03-28 01:51 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
>          String line;
String line을 먼저 선언한 이유는 while문의 조건식에서 BufferedReader.readLine()의 결과값을 저장 받음과 동시에 공백을 equals로 체크하기 위하여 미리 선언 하였습니다.

2022-03-28 02:01 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
> +        initURL();
init는 초기값을 설정하거나, 내용을 초기화할 때 많이들 사용하는 것으로 알고 있었습니다.
때문에 두 메소드가 각각 requestLine 초기값을 설정하는 역할과
URL 초기값을 설정하는 역할이라 생각하였기에 init를 사용하게 되었습니다.

행여 지적하시는 부분이 init가 추상적으로 여겨져서 더욱 명확한 느낌의 메소드명을 짓는것을 추천하시는 것인지에 대해 여쭤보고 싶습니다.

2022-03-28 02:09 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
>      public Request(BufferedReader bufferedReader) throws IOException {
InputStream의 정보를 담고 있기에 BufferedReader만 가져오면 Request클래스에서 정보를 받아오고 가공하기 위해 사용하게 되었습니다.

2022-03-28 02:10 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
> +            String[] temp = line.split(" ");
변수 네이밍에 좀 더 신경 쓰겠습니다. 이번에 반영할 때 수정하겠습니다!

2022-03-28 02:10 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
> +        while (!("").equals(line = bufferedReader.readLine())) {
엇...감사합니다 수정하겠습니다!

2022-03-28 02:16 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
> +    }
당초 저희는 필드멤버를 초기화하고, 로그를 띄우기 위한 용도로만 생성자를 사용하고 있습니다.
말씀해주신 너무 많은 일이라는게 메소드를 여러개로 분리해보라는 말씀일인지 여쭤봐도 될까요?

2022-03-28 02:18 UTC, fpzk5656 commented on src/main/java/webserver/Request.java
>      }
Request 클래스 안에 상태를 표기할 수 있는 필드멤버를 추가해보겠습니다.

2022-03-28 02:23 UTC, fpzk5656 commented on src/main/java/webserver/RequestHandler.java
>      }
저희는 RequestHandler 객체에서 도메인 객체 저장이 바로 가능하였기에 따로 분리하지 않아도 좋다고 생각하였습니다.

2022-03-28 02:33 UTC, fpzk5656 commented on src/main/java/webserver/Response.java
> +    private static final Logger log = LoggerFactory.getLogger(Response.class);
도메인 객체에 대한 정의를 좀 더 공부해보겠습니다.
일단 log를 만든 이유는 응답을 사용하기 위한 클래스인 Response에서 사용하는 메소드의 예외처리를 위함입니다.

2022-03-28 02:36 UTC, fpzk5656 commented on src/main/java/webserver/Response.java
> +    private DataOutputStream dos;
DataOutputStream 이 필드로 관리 될 필요는 없었다는 지적이신 것으로 알아들었는데.
이에 따라 수정토록 하겠습니다.

2022-03-28 02:38 UTC, fpzk5656 commented on src/main/java/webserver/Response.java
> +    }
좀 더 고민해보고 수정해보겠습니다.

2022-03-28 02:40 UTC, fpzk5656 commented on src/main/java/webserver/URL.java
> +    private static final String SIGN_UP_PAGE = "http://localhost:8080/user/form.html";
해당 주소가 아니어도 받아서 범용적인 URL 구조를 짜보겠습니다.

2022-03-28 02:40 UTC, fpzk5656 commented on src/main/java/webserver/URL.java
> +    public void setRedirectSignUpPAGE() {
수정하겠습니다.

2022-03-28 02:40 UTC, fpzk5656 commented on src/main/java/webserver/URL.java
> +    }
넵! 수정하겠습니다.

2022-03-28 14:45 UTC, ksundong commented on src/main/java/util/RequestLineUtil.java
> +        String[] strList = requestLine.split(" ");
넵 좋습니다.

2022-03-28 14:53 UTC, ksundong commented on src/main/java/webserver/Request.java
> +        initURL();
네 보통 `init`은 초기화시에 많이 사용됩니다.
다만 두 메서드는 초기화를 한다기 보다는, 다른 일들을 수행해주고 있습니다.
해당 역할이 정말 초기화인지 다시 한 번 생각해보시면 좋겠습니다.
`init`이 추상적이진 않고, 해당 메서드가 하는 일과 `init`이 어색한 조합이라 리뷰드렸습니다.

2022-03-28 14:55 UTC, ksundong commented on src/main/java/webserver/Request.java
>      public Request(BufferedReader bufferedReader) throws IOException {
왜 가공을 `Request`가 생성자에서 해주어야 하나요?
생성자가 해야하는 일은 무엇일까요?

2022-03-28 14:57 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    }
단일 책임 원칙에 대해서 생각해보세요.
생성자가 해야하는 일은 무엇일까요?

2022-03-28 14:58 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
>      }
그럼 분리해야하는 경우는 언제라고 생각하시나요~?

2022-03-28 14:59 UTC, ksundong commented on src/main/java/webserver/Response.java
> +    private static final Logger log = LoggerFactory.getLogger(Response.class);
예외처리를 위해서 로거가 필요한가요?

2022-03-28 15:00 UTC, ksundong commented on src/main/java/webserver/Response.java
> +    private DataOutputStream dos;
음... 저는 이유를 물었는데...

2022-03-28 15:25 UTC, ksundong approved these changes
고생하셨습니다~

2022-03-28 15:25 UTC, ksundong commented on src/main/java/webserver/Request.java
> +    }
깔끔해지만 결국 이 클래스는 딱히 하는 역할이 없어져버렸네요. 좀 더 고민해봅시다~

2022-03-28 15:25 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    private final String signUpPage;
host와 port는 실행하기 전에 지정될 것 같은데 아닌가요?

2022-03-28 15:25 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    }
setRedirect 라는 이름은 어색한 것 같습니다~

2022-03-28 15:25 UTC, merged

2022-03-29 09:21 UTC, bugpigg commented on src/main/java/webserver/URL.java
> +    }
넵 `setPathToHomePage` 와 같은 형식으로 수정하겠습니다.

2022-03-29 09:23 UTC, bugpigg commented on src/main/java/webserver/URL.java
> +    private final String signUpPage;
`URL` 객체를 정의하는 시점에, 
`Request`로부터 host와 port를 입력 받아 지정하고 있습니다!

2022-03-29 15:23 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    private final String signUpPage;
서버 관점에서 런타임에 host와 port가 변경될 수 있나요?

2022-03-29 15:23 UTC, ksundong commented on src/main/java/webserver/URL.java
> +    }
`change`가 낫겠죠. `get`, `set`을 잊고 네이밍 하는것을 추천드립니다.

2022-03-30 06:37 UTC, bugpigg commented on src/main/java/webserver/URL.java
> +    }
넵 알겠습니다!

2022-03-30 07:08 UTC, fpzk5656 commented on src/main/java/webserver/URL.java
> +    private final String signUpPage;
서버 관점에서는 host와 port가 변경 되지 않으니,
상수로 지정해서 사용하겠습니다.