[Louie, Lee] 웹서버 2단계 - GET으로 회원가입 PR입니다.
codesquad-members-2022/java-was pull request #44
Opened 2022-03-28 01:51 UTC by street62

안녕하세요 리뷰어님! Louie, Lee입니다.
웹서버 2단계 미션인 'GET으로 회원가입하기' PR입니다.
1단계 머지 이전에 2단계 구현을 시작해서, 1단계 피드백 반영 커밋은 조금 더 후반부에 있습니다. 
README에는 각자 미션을 진행하면서 학습한 부분들을 정리했습니다.

그럼 이번에도 잘 부탁드립니다.
감사합니다!

2022-03-28 13:02 UTC, tmdgusya requested changes
웹 서버 미션 2단계 진행하느라 고생많으셨습니다 👍 
기본적으로 Http 에 관해서 공부해보고 생각해볼수 있는 시간이 되시길 바래요.
몇가지 생각할점과 고쳐보면 좋을점 그리고 공부하면 좋은 점들에 대해서 리뷰 남겨놨어요.

한번 확인해보시고 반영부탁드려요 :)

2022-03-28 13:02 UTC, tmdgusya commented on README.md
> +이후 rebase 과정에서 merge와 마찬가지로 변경사항 충돌이 일어날 수 있는데요. merge와 rebase의 충돌이 다른 점은, merge는 하나의 머지 커밋을 만들면서 충돌사항이 한 커밋에 모이기 때문에 충돌을 해결하고 그대로 commit하면 되지만, rebase는 병합되어 들어오는 브랜치의 커밋을 하나하나 차례로 병합해 나가는 방식이기 때문에,
공부하셨군요 ㅎㅎ

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/http/HttpRequest.java
> +        while (!(line.equals("") || line == null)) {
이건 생각해보면 좋은 점이라 가볍게 언급정도 해봅니다 ㅎㅎ
저 같은 경우에는 아래와 같이 조건문이 무언가 알기 힘들다고 여겨지면 
```java
(line.equals("") || line == null)
```

를 함수로 분리해 놓는 편이에요

`if(XXXCondition())` 이런식으로요

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/http/HttpRequest.java
> +        while (!(line.equals("") || line == null)) {
근데 지금 같은 경우는 조금만 읽어보면 알수있다고 판단되긴해서 상관은 없으나
가독성을 올리고 싶다면 하셔도 좋습니다 ㅎㅎ

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/http/HttpRequest.java
> +    private Map<String, String> paramMap;
저는 이런 경우 `Map<String, String>` 을 RequestParam 등의 1급 컬렉션으로 분리하는데요.
이건 미션과는 별개이니 한번 생각해보시면 좋을거 같아요 ㅎㅎ
이런 방법도 있다 정도라고 생각하시면 좋을거 같아요.

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/http/HttpResponse.java
> +        responseHeader += ("\r\n");
StringBuilder 를 사용하는게 좋지 않을까요?

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/util/HttpRequestUtils.java
> +        if (splitedPath.length != 2) {
여기서 2 는 어떤의미일까요? 매직 넘버같지 않나요?

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/util/IOUtils.java
> +public class IOUtils {
IOUtils 는 정확히 어떤걸하는 클래스인가요?

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/webserver/RequestHandler.java
> +            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(in, "UTF-8"));
`bufferedReader` 도 close 해줘야 하지 않나요?

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/controller/MyController.java
> +public interface MyController {
인터페이스로 정의하셨군요 ㅎㅎ
이런거 좋은거 같아요~! 자신만의 프레임워크에서 Controller 가 요청을 처리하려면 `process` 를 가져야 한다 👍

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/controller/SaveUserController.java
> +public class SaveUserController implements MyController {
좋습니다. 하나하나 만들어가는거죠 ㅎㅎ 👍

2022-03-28 13:02 UTC, tmdgusya commented on src/main/java/was/http/HttpResponse.java
> +        }
테스트용 같긴한데 이런건 어떻게 처리할 수 있을까 고민하는게 좋아보여요 ㅎㅎ
지금은 return 이 뭔가 Webapp 의 File 을 불러오는 느낌이라, 어떻게 해야 String Byte 도 보내고 할지 생각홰보는게 좋을거 같아요.

2022-03-31 06:51 UTC, honux77 commented
이거 현재 별 조치는 없지만 시간이 오래 된 관계로 제가 머지할게요.

2022-03-31 06:51 UTC, merged