[Sammy & ikjo] 웹서버 4단계 - 쿠키를 이용한 로그인 구현
codesquad-members-2022/java-was pull request #46
Opened 2022-03-28 02:36 UTC by ikjo93

안녕하세요!! Sammy & ikjo 팀입니다!!

"웹서버 4단계 - 쿠키를 이용한 로그인 구현" 구현 부분과 관련하여, 작성한 소스 코드 파일을 첨부드리오니 확인부탁드립니다. :)

아울러 미션을 진행하면서 새롭게 알게 되었던 부분 등 미션 관련 사항은 별도 README 파일에 작성하였습니다!!

감사합니다!!

### 기능요구사항

- [x] 회원가입한 사용자로 로그인을 할 수 있어야 한다.
  - [x] “로그인” 메뉴를 클릭하면 http://localhost:8080/user/login.html 으로 이동해 로그인할 수 있다.
  - [x] 로그인이 성공하면 index.html로 이동하고, 로그인이 실패하면 /user/login_failed.html로 이동해야 한다.

### 프로그래밍 요구사항

- [x] 앞 단계에서 회원가입할 때 생성한 User 객체를 DataBase.addUser() 메서드를 활용해 메모리에 저장한다.
  - 필요에 따라 Database 클래스의 메소드나 멤버변수를 수정해서 사용한다.
- [x] 아이디와 비밀번호가 같은지를 확인해서 로그인이 성공하면 응답 header의 Set-Cookie 값을 sessionId=적당한값으로 설정한다.
- [x] Set-Cookie 설정시 모든 요청에 대해 Cookie 처리가 가능하도록 Path 설정 값을 /(Path=/)로 설정한다.
- [x] 응답 header에 Set-Cookie값을 설정한 후 요청 header에 Cookie이 전달되는지 확인한다.

### 추가 요구 사항

- [x] (선택) 로그아웃을 구현한다.

2022-03-28 16:08 UTC, ksundong requested changes
안녕하세요. Sammy & ikjo, 리뷰어 dion입니다.

4단계 미션 수행하느라 정말 고생많으셨습니다.

몇가지 수정했으면 하는 사항이 있어 변경요청 드립니다. 궁금하신점은 코멘트 남겨주시고, 변경이 완료된 다음 다시 리뷰요청을 해주세요~

2022-03-28 16:08 UTC, ksundong commented on webapp/js/scripts.js
> +// });
이 코드는 왜 추가된걸까요?

2022-03-28 16:08 UTC, ksundong commented on README.md
> +  - http 응답을 통해 쿠키를 만료시킬 때에도 대상 쿠키와 동일한 path를 명시해 주어야 정상적으로 만료시킬 수 있다.
:+1:

2022-03-28 16:08 UTC, ksundong commented on src/main/java/db/DataBase.java
> +        User user;
미리 선언해줄 필요가 전혀 없어보여요.

2022-03-28 16:08 UTC, ksundong commented on src/main/java/db/DataBase.java
> +        return false;
한줄로 충분히 표현가능해보여요.

2022-03-28 16:08 UTC, ksundong commented on src/main/java/db/Sessions.java
> +public class Sessions {
해당 클래스는 `Utiltiy`  클래스인가요? 과연 그럴 필요가 있을까요..?

2022-03-28 16:08 UTC, ksundong commented on src/main/java/model/User.java
> +    }
왜 `null` 여부까지 검사해야하나요??

2022-03-28 16:08 UTC, ksundong commented on src/main/java/webserver/HttpRequest.java
> +        if ((cookies = httpRequest.getHeader("Cookie")) != null) {
선언 부분과 할당부분을 나눠주신 이유가 있나요? 너무 읽기 힘든 것 같아요.

2022-03-28 16:08 UTC, ksundong commented on src/main/java/webserver/HttpSession.java
> +    private final Map<String, Object> attributes = new ConcurrentHashMap<>();
왜 `ConcurrentHashMap` 을 사용해주셨나요?

2022-03-28 16:08 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +                log.debug("httpRequest.getCookies() = " + httpRequest.getCookies());
문자열 연산 대신 `{}` 을 활용해주세요. `logger`의 성능 문제도 한 번 찾아보세요.

2022-03-28 16:08 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
점점 많아지는데 어떻게 하면 좋을까요? 이건 지금 단계에서 꼭 해결해보셨으면 좋겠네요.

2022-03-29 01:42 UTC, astraum commented on webapp/js/scripts.js
> +// });
제공된 html 파일들의 로그아웃 버튼들의 링크가 "#"으로 지정되어 있어서 일괄적으로 `../user/logout` 경로를 할당해 주려고 했습니다. 

미봉책이지만 미션 주제인 서버에 집중하기 위해 편의상 이렇게 했습니다. 사실, 버튼이 동작해야 한다는 요구사항이 없었으므로 굳이 넣지 않아도 되는 코드였지만, 동작 확인을 위해 주소창에 일일이 `/user/logout`을 치는 것보다 버튼을 누르는 게 편했습니다 (단위 테스트와는 별개로 개발자 도구에서 쿠키 내역을 보고 싶었습니다). 

윗줄의 콘솔 로그와 아래의 주석은 찌꺼기인데 깜박하고 지우지 않았습니다.

2022-03-29 02:21 UTC, astraum commented on src/main/java/db/Sessions.java
> +public class Sessions {
기본 제공된 코드에서 유저 데이터베이스`DataBase`가 유틸리티 클래스로 정의되어 있어서 세션 저장소도 일단 비슷하게 작성해 보았습니다. 

유틸리티 클래스일 필요가 있는가 하면, 그럴 필요는 없다고 생각합니다. 오히려 글로벌하게 접근해서 내용을 변경할 수 있는 자료구조라는 점이 문제가 될 수 있다고 생각하여 개선방안을 모색하고 있지만 아직 만족스러운 해법이 떠오르지 않아 계속 고민하고 있습니다. 

예를 들어, 저장소의 인스턴스를 생성한다면 어디에서 생성하고 어디로 넘겨주어야 할까요? 만약 싱글톤 패턴을 사용한다고 하면, getInstance 스태틱 메서드를 통해 글로벌하게 접근 가능하다는 점은 마찬가지일 것 같은데 개선되는 것이 맞을까요?

혹시 도움이 될 만한 방향성이나 키워드를 제시해 주실 수 있을까요?

2022-03-29 02:24 UTC, astraum commented on src/main/java/model/User.java
> +    }
검사할 필요가 없습니다. String::equals 메서드의 인자로 `null` 값이 들어가면 결과는 어차피 `false`이기 때문입니다.

2022-03-29 02:42 UTC, astraum commented on src/main/java/webserver/HttpRequest.java
> +        if ((cookies = httpRequest.getHeader("Cookie")) != null) {
if 조건문 안에 `httpRequest.getHeader("Cookie") != null`만 넣었다가, if 문 내부에서 getHeader의 반환값이 다시 쓰이기 때문에 변수명을 할당해 주었습니다. if 조건문 안에서 변수 할당은 가능하지만 선언은 불가능하여 선언만 외부로 꺼냈는데, 다시 살펴보니 선언 시점에서 할당까지 해주고 조건문 안에는 변수명만 넣어주는 편이 더 읽기 좋다는 것을 깨달았습니다.

2022-03-29 02:59 UTC, astraum commented on src/main/java/webserver/HttpSession.java
> +    private final Map<String, Object> attributes = new ConcurrentHashMap<>();
1명의 유저가 브라우저 창을 여러개 띄우고 접속하면 여러 개의 요청(스레드)이 하나의 HttpSession에 동시 접근하는 경우도 발생할 수 있다고 생각하여 `ConcurrentHashMap`을 사용했습니다.

2022-03-29 03:03 UTC, astraum commented on src/main/java/webserver/RequestHandler.java
> +                log.debug("httpRequest.getCookies() = " + httpRequest.getCookies());
앗차, `soutv` 로 시험삼아 찍어봤다가 별 생각없이 메서드만 `log.debug` 로 바꿔봤던 건데 이걸 방치해놨었네요. 

필요 없는 부분이라 5단계에서 제거했습니다!

2022-03-29 03:05 UTC, astraum commented on src/main/java/webserver/RequestHandler.java
> +            }
5단계에서 매핑을 이용하여 정리했습니다! 5단계 PR을 기대해주세요! 😉

2022-03-29 03:20 UTC, astraum commented
@ksundong 디온, 피드백 반영하여 다시 리뷰 요청 드립니다! 

`RequestHandler::run` 의 if 블록들은 5단계 진행하면서 매핑 형식으로 개선해 놓았습니다!

2022-03-29 15:17 UTC, ksundong commented on src/main/java/db/Sessions.java
> +public class Sessions {
세션은 어디서 관리해야하는지 고민해보시고, 이를 상태로 관리해주면 되지 않을까요?

2022-03-29 15:21 UTC, ksundong approved these changes
고생많으셨습니다.
살짝 의아한 부분이 있어 코멘트 남겼습니다~

2022-03-29 15:21 UTC, ksundong commented on src/main/java/db/DataBase.java
> +                .orElse(false);
`userId`가 `null`이 전달될 가능성이 있어서 이렇게 짜주신건가요...?

2022-03-29 15:21 UTC, merged

2022-03-30 02:24 UTC, astraum commented on src/main/java/db/DataBase.java
> +                .orElse(false);
예, 로그인 폼이 공백일 경우 `userId` 로 `null` 이 들어오는 것을 확인했습니다. 미션 시작 시 제공된 메서드 중 `getKeyValue` 메서드가 쿼리 문자열을 split 하였을 때, 토큰이 2개가 아니면 Pair 객체 대신 `null` 을 리턴하도록 만들어져 있었습니다. 

또한 ConcurrentHashMap 객체는 `null` 을 허용하지 않기 때문에 `get(null)` 메서드를 전송하면 `null` 을 리턴하는 대신 `NPE` 😱 를 발생시킵니다.  

인자에 대해서 `null` 체크를 남발하는 것이 가독성과 유지보수성을 해친다고 들었기 때문에, 이 부분을 개선하려면 어떻게 하는 것이 좋을지 고민해 보았습니다. 

1. 인자에 `@Nonnull` 애너테이션 추가: 해당 애너테이션을 추가해도 `null` 이 들어오는 것 자체를 막을 수는 없고, `matchesExistingUser` 메서드 내부에서 이루어지는 `null` 체크를 탐지할 뿐, 메서드를 호출하는 위치에서 인자가 `null` 일 가능성을 IDE 나 컴파일러가 탐지하지는 못했습니다. 
2. `Objects.requiresNonNull` 메서드는 `null` 체크를 수동으로 하는 것과 마찬가지이고, `null` 이 들어올 경우 무조건 `NPE` 를 발생시킵니다. 
3. `getKeyValue` 메서드가 `null` 이 아닌 기본값을 리턴하도록 한다. 
4. 메서드를 호출하는 위치에서 인자를 넘기기 전에 `null` 을 체크하고, `null` 일 경우의 조건문을 따로 작성한다.  
5. 메서드를 호출하는 위치에서 userId 를 할당할 때 (`userId = loginForm.get("userId")`) get 대신 getOrDefault 를 써서 `null` 이 아닌 기본값(빈 문자열?)을 넣어준다.  

`null` 체크에 관해서는 이전에 스프링 카페 리뷰에서도 언급하신 적이 있어서 짬짬이 공부하고 있지만 아직 어떻게 처리하면 좋을지 명확한 구상이 떠오르지는 않습니다. 좀 더 연구해보겠습니다.

2022-04-01 11:22 UTC, ksundong commented on src/main/java/db/DataBase.java
> +                .orElse(false);
음 개인적으로 `null`이 될 수 없도록 모든 data의 시작점에서 `null`이 될 수 없도록 해주는게 좋아보입니다.