[후 & Hwi] 웹서버 3단계 - POST로 회원 가입
codesquad-members-2022/java-was pull request #47
Opened 2022-03-28 05:33 UTC by hwicode

안녕하세요~ 후 앤 Hwi입니다.
3단계 요구사항 구현 완료하여 PR 보냅니다.
저희 코드를 보시고 리뷰 남겨주시는 분들께 감사드립니다.
자세한 내용은 README를 참고해주세요!
행복한 하루 되세요!😄

2022-03-28 16:19 UTC, ksundong requested changes
안녕하세요. 후 & Hwi, 리뷰어 dion입니다.

3단계 미션 진행하느라 고생많으셨습니다.

요구사항이 지켜지지 않은 부분이 있어 변경요청 드립니다. 고치시고 다시 리뷰 요청해주세요~ 고생많으셨습니다~

2022-03-28 16:19 UTC, ksundong commented on webapp/index.html
> +<!--		<link href="css/styles.css" rel="stylesheet">-->
왜 주석처리 해주셨나요?

2022-03-28 16:19 UTC, ksundong commented on README.md
> +- [X] 가입 후 index.html 페이지로 이동한다.
마크다운 문법에서 목록은 줄간 간격을 두지 않습니다~

2022-03-28 16:19 UTC, ksundong commented on README.md
> +- 초기에는 log를 통해 에러가 난 부분을 찾고자 하였는데 산토리 선생님께서 디버거를 이용하셔서 문제를 해결하시는 모습을 보고 디버거를 사용해야겠다는 생각이 들었습니다.
:100:

2022-03-28 16:19 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +            }
매 요청마다 분기를 태우는 구조는 과연 유지보수하기 괜찮을까요?

2022-03-28 16:19 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
>          }
이런 방식으로 예외처리를 해주는건 괜찮을까요? 좀 더 나은 방법은 어떤 방법일까요?

2022-03-28 16:19 UTC, ksundong commented on src/test/java/util/HttpRequestUtilsTest.java
> +        String url = "/create";
해당 테스트에서 사용되는 url은 url이 맞을까요? 한 번 URL이 무엇인지에 대해서 학습해보시고 정리해보시기 바랍니다~

2022-03-28 16:19 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +    }
요구사항이 지켜지지 않은 것으로 보여요~
> 같은 ID로 가입을 시도할 경우 가입되지 않고 가입 페이지로 이동한다.

2022-03-29 01:49 UTC, hwicode commented on webapp/index.html
> +<!--		<link href="css/styles.css" rel="stylesheet">-->
`software caused connection abort: socket write error` 에러가 발생했을 때 문제가 된 부분을 명확하게 보기 위해서 `css`파일이나 `js`파일들을 주석처리했습니다.

2022-03-29 01:50 UTC, hwicode commented on README.md
> +- [X] 가입 후 index.html 페이지로 이동한다.
줄 간 간격을 수정하겠습니다!

2022-03-29 01:56 UTC, hwicode commented on src/main/java/webserver/RequestHandler.java
> +            }
다른 방법을 생각해보겠습니다!

2022-03-29 02:47 UTC, hwicode commented on src/main/java/webserver/RequestHandler.java
> +    }
요구사항을 제대로 보지 못했습니다 죄송합니다
같은 ID로 가입을 시도할 경우 가입되지 않고 가입 페이지로 가도록 수정하겠습니다!

2022-03-29 03:02 UTC, hwicode commented on src/main/java/webserver/RequestHandler.java
>          }
`run()` 메서드의 `catch`문에서 모든 `NPE`에 대한 예외처리를 한 번에 해결하는 방법은 부적절한 것 같습니다.
이렇게 하기보다 `null`이 생길만한 부분들에서 각자 처리해야할 내용별로 확실한 예외처리를 하는 방법이 나은 것 같습니다.

2022-03-29 03:05 UTC, hwicode commented on src/test/java/util/HttpRequestUtilsTest.java
> +        String url = "/create";
README에 URL에 대한 내용을 정리하겠습니다!

2022-03-29 15:27 UTC, ksundong approved these changes
고생하셨습니다.
복잡한 로직은 다음 단계에서 개선되기를 기대해보겠습니다~

2022-03-29 15:27 UTC, ksundong commented on src/main/java/webserver/RequestHandler.java
> +                });
엄청 코드가 복잡해졌네요~~

2022-03-29 15:27 UTC, merged

2022-03-30 01:34 UTC, hwicode commented on src/main/java/webserver/RequestHandler.java
> +                });
다음 단계에서 개선하겠습니다!