[케이 & Shine] 5단계 - 동적 HTML
codesquad-members-2022/java-was pull request #65
Opened 2022-03-31 05:35 UTC by zbqmgldjfh

# 안녕하세요 리뷰어님!! K, Shine 팀 입니다.
저희 팀의 리뷰를 해주셔서 감사합니다!!!

## 질문
저희 팀이 로그인 처리를 위해서 LoginFilter 를 구현하게 되었는데, 기능은 정상 작동 하지만, 전반적으로 한눈에 들어오지 않는 코드가 되었다고 생각합니다.
메서드 단위로 작게 쪼게려 노력은 했지만, 로직이 이분법적으로 매우 혼잡하여 보는 사람으로 하여금 이해하기 어려울 것 같은 메서드가 탄생되었습니다.

해당 LoginFilter 에 대한 전반적인 리뷰를 부탁드립니다.

## Step04 리뷰 반영
- [x] DataBase.findUserById "ddd" 수정하기
- [x] Session DB에서 직접 세션 생성하도록 변경
- [x] LogoutServlet.getSessionId에서 상수 사용하기 (SESSION_ID_IDX=1)

## Step05 TODO list
- [x] 로그인 상태일 경우 User 목록 출력
- [x] 로그인 하지 않은 상태면 Login으로 이동

2022-04-02 08:36 UTC, tmdgusya requested changes
학습을 열심히 하신거 같아 좋네요 👍 
Filter 와 Interceptor 차이는 시간이 나실때 공부해보셔도 좋을거 같아요

몇가지 간단하게 수정할 부분만 수정하고 넘어가시죠

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/db/DataBase.java
> +                    throw new DuplicatedUserException(ALREADY_REGISTER_USER_ERROR);
👍

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/db/Session.java
> +        String sessionId = UUID.randomUUID().toString();
특이하네요 ㅎㅎ
JSESSION 보면서 떠올렸나보군요 ㅎㅎ. 재밌는거 같아요.

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/db/Session.java
> +    public static String save(User value) {
User 만 넣을수 있는건 아쉽네요 ㅎㅎ Object 로 하는건 어떨까요?

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/db/Session.java
> +    public static boolean isLoginUser(String sessionId) {
Web Server 의 Session 이라면 이런 메소드는 없어도 되지 않을까 싶어요.

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/filter/Filter.java
> +    public boolean doFilter(HttpRequest request, HttpResponse response);
👍

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/filter/Filter.java
> +    public boolean doFilter(HttpRequest request, HttpResponse response);
Spring Filter 를 학습하시고 만드신거 같네요 ㅎㅎ
Filter 와 Interceptor 차이를 공부해보셔도 좋을거 같아요.

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/UserListServlet.java
> +        Collection<User> users = DataBase.findAll();
Collection 으로 받으시는 이유가 있나요?

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/filter/LoginFilter.java
> +            if (Session.isLoginUser(sessionId)) {
굳이 2뎁스로 나눌필요는 없을것 같기도 해요 ㅎㅎ

(sessionId != null && Session.isLoginUser(sessionId))

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/filter/LoginFilter.java
> +            return splits[1].substring(10);
이건혹시 어떤걸 가져오는 건가요? 10 이라는 숫자가 어떤걸 의미하는지 잘 모르겠어서요.

2022-04-02 08:36 UTC, tmdgusya commented on src/main/java/servlet/filter/LoginFilter.java
> +            return splits[1].substring(10);
매직넘버인거 같아 상수로 관리하면 좋을거 같아요

2022-04-03 01:57 UTC, zbqmgldjfh commented on src/main/java/db/Session.java
> +        String sessionId = UUID.randomUUID().toString();
ㅎㅎ 구현하면서 아무래도 원래 기존의 Servlet 코드들을 살펴보면서 구현했다보니 ㅎㅎ
JSESSION 또한 Spring 공부할때 사용했었던 기능이라 비슷하게 조금이나마 구현하게 되었습니다 ㅎㅎ

2022-04-03 02:00 UTC, zbqmgldjfh commented on src/main/java/db/Session.java
> +    public static String save(User value) {
좋은 것 같습니다. 미션으로만 생각하다보니, 단순하게 User만 저장해야 된다 생각했는데, Object를 사용하여 범용적으로 받는것이 더 좋은것 같습니다!! 수정하겠습니다!!

2022-04-03 02:09 UTC, zbqmgldjfh commented on src/main/java/db/Session.java
> +    public static boolean isLoginUser(String sessionId) {
아하! Session 자체에 부합하는 기능이 아니긴 하군요...
물론 처음에는 OOP 적으로 객체에게 질문을 날리기 위해 만든 함수이기는 하지만, 사실 Session에게 직접 로그인 하였는지 확인하는 메서드를 날리기 보다는, 기존의 실제 서버의 session 처럼 해당 key값을 갖는 value를 반환시켜 이를 활용하는것이 더 좋을것 같습니다.
사용하는 쪽에서는 session.getattribute 와 같이 사용하도록 수정하겠습니다.

2022-04-03 02:15 UTC, zbqmgldjfh commented on src/main/java/servlet/filter/Filter.java
> +    public boolean doFilter(HttpRequest request, HttpResponse response);
넵 ㅎㅎ Spring의 (filter - dispatcherServlet - interceptor - handler) 구조에 대하여 학습하였습니다!

2022-04-03 02:20 UTC, zbqmgldjfh commented on src/main/java/servlet/UserListServlet.java
> +        Collection<User> users = DataBase.findAll();
원래는 List와 같은 종류로 casting 해보려 했는데, 이게 DataBase가 ConcurrentHashMap 을 사용하고 있어서 values()로 반환하는 기본값이 Collection 이였습니다. 따로 stream을 처리하여 collect을 적용하여 List로 반활할수도 있어지만, 우선을 기본값을 사용하기로 했었습니다!!

2022-04-03 02:22 UTC, zbqmgldjfh commented on src/main/java/servlet/filter/LoginFilter.java
> +            if (Session.isLoginUser(sessionId)) {
감사합니다 ㅎㅎ 바로 적용시키겠습니다!!!

2022-04-03 02:26 UTC, zbqmgldjfh commented on src/main/java/servlet/filter/LoginFilter.java
> +            return splits[1].substring(10);
넵 의미가 있는 상수로 분리하도록 하겠습니다!!

2022-04-03 08:14 UTC, tmdgusya commented
고생하셨어요 ㅎㅎ

2022-04-03 08:14 UTC, merged